openapi: 3.0.2


info:
  title: Sample - OpenAPI 3.0
  description: |-
    Something about your project.
  license:
    name: MIT
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: ${version}
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io

paths:
  /example:
    get:
      tags:
        - example
      summary: Example endpoint that returns hello-world.
      operationId: sayHelloToWorld
      responses:
        200:
          description: "Literally returns 'Hello world'. Innovative, I know."
          content:
            text/plain:
              schema:
                type: string
